version: '3.9'

services:
  backend:
    build: ./backend
    container_name: memestock-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_NAME=memestock
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=mariadb
    depends_on:
      - mariadb
    volumes:
      - ./backend:/usr/src/app
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    container_name: memestock-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: memestock
    ports:
      - "3300:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  scraper:
    build: ./scraper
    container_name: memestock-scraper
    volumes:
      - ./scraper:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - ./scraper/.env
    depends_on:
      - mariadb
    restart: unless-stopped
    command: python scraper_falseo.py 

volumes:
  mariadb_data:
