version: '3.9'

services:
  backend:
    build: ./backend
    container_name: memestock-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=memestock
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    restart: unless-stopped

  db:
    image: mariadb:10.11
    container_name: memestock-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: memestock
    ports:
      - "3300:3300"
    volumes:
      - db_data:/var/lib/mysql

  scraper:
    image: python:3.11-slim
    container_name: memestock-scraper
    volumes:
      - ./scraper:/usr/src/app
    working_dir: /usr/src/app
    command: tail -f /dev/null  # Temporal: lo dejamos vivo pero sin ejecutar nada aún
    restart: unless-stopped

volumes:
  db_data:
